FROM golang:1.24-alpine AS builder
RUN apk add --no-cache git
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o /bin/iot-sim ./cmd/iot-sim

FROM alpine:3.19
COPY --from=builder /bin/iot-sim /iot-sim
ENTRYPOINT ["/iot-sim"]
