// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: server.proto

// Package name for the protobuf definitions

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HllService_Insert_FullMethodName      = "/hllservice.HllService/Insert"
	HllService_GetEstimate_FullMethodName = "/hllservice.HllService/GetEstimate"
	HllService_Reset_FullMethodName       = "/hllservice.HllService/Reset"
	HllService_GetSketch_FullMethodName   = "/hllservice.HllService/GetSketch"
	HllService_MergeSketch_FullMethodName = "/hllservice.HllService/MergeSketch"
	HllService_Health_FullMethodName      = "/hllservice.HllService/Health"
)

// HllServiceClient is the client API for HllService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// HllService provides RPC methods to interact with a HLL++ sketch.
type HllServiceClient interface {
	// Inserts a single IP into the sketch.
	Insert(ctx context.Context, in *InsertRequest, opts ...grpc.CallOption) (*InsertResponse, error)
	// Gets the current cardinality estimate from the sketch.
	GetEstimate(ctx context.Context, in *GetEstimateRequest, opts ...grpc.CallOption) (*GetEstimateResponse, error)
	// Resets the sketch to its empty, initial state (sparse).
	Reset(ctx context.Context, in *ResetRequest, opts ...grpc.CallOption) (*ResetResponse, error)
	// Retrieves the raw sketch data for merging on an aggregator.
	// This is the "PULL" method for aggregation.
	GetSketch(ctx context.Context, in *GetSketchRequest, opts ...grpc.CallOption) (*Sketch, error)
	// Merges an incoming sketch into this node's local sketch.
	// This is the "PUSH" method for aggregation.
	MergeSketch(ctx context.Context, in *MergeRequest, opts ...grpc.CallOption) (*MergeResponse, error)
	// Standard health check for Kubernetes liveness/readiness probes.
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type hllServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHllServiceClient(cc grpc.ClientConnInterface) HllServiceClient {
	return &hllServiceClient{cc}
}

func (c *hllServiceClient) Insert(ctx context.Context, in *InsertRequest, opts ...grpc.CallOption) (*InsertResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InsertResponse)
	err := c.cc.Invoke(ctx, HllService_Insert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hllServiceClient) GetEstimate(ctx context.Context, in *GetEstimateRequest, opts ...grpc.CallOption) (*GetEstimateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEstimateResponse)
	err := c.cc.Invoke(ctx, HllService_GetEstimate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hllServiceClient) Reset(ctx context.Context, in *ResetRequest, opts ...grpc.CallOption) (*ResetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResetResponse)
	err := c.cc.Invoke(ctx, HllService_Reset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hllServiceClient) GetSketch(ctx context.Context, in *GetSketchRequest, opts ...grpc.CallOption) (*Sketch, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Sketch)
	err := c.cc.Invoke(ctx, HllService_GetSketch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hllServiceClient) MergeSketch(ctx context.Context, in *MergeRequest, opts ...grpc.CallOption) (*MergeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MergeResponse)
	err := c.cc.Invoke(ctx, HllService_MergeSketch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hllServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, HllService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HllServiceServer is the server API for HllService service.
// All implementations must embed UnimplementedHllServiceServer
// for forward compatibility.
//
// HllService provides RPC methods to interact with a HLL++ sketch.
type HllServiceServer interface {
	// Inserts a single IP into the sketch.
	Insert(context.Context, *InsertRequest) (*InsertResponse, error)
	// Gets the current cardinality estimate from the sketch.
	GetEstimate(context.Context, *GetEstimateRequest) (*GetEstimateResponse, error)
	// Resets the sketch to its empty, initial state (sparse).
	Reset(context.Context, *ResetRequest) (*ResetResponse, error)
	// Retrieves the raw sketch data for merging on an aggregator.
	// This is the "PULL" method for aggregation.
	GetSketch(context.Context, *GetSketchRequest) (*Sketch, error)
	// Merges an incoming sketch into this node's local sketch.
	// This is the "PUSH" method for aggregation.
	MergeSketch(context.Context, *MergeRequest) (*MergeResponse, error)
	// Standard health check for Kubernetes liveness/readiness probes.
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedHllServiceServer()
}

// UnimplementedHllServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHllServiceServer struct{}

func (UnimplementedHllServiceServer) Insert(context.Context, *InsertRequest) (*InsertResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Insert not implemented")
}
func (UnimplementedHllServiceServer) GetEstimate(context.Context, *GetEstimateRequest) (*GetEstimateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEstimate not implemented")
}
func (UnimplementedHllServiceServer) Reset(context.Context, *ResetRequest) (*ResetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Reset not implemented")
}
func (UnimplementedHllServiceServer) GetSketch(context.Context, *GetSketchRequest) (*Sketch, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSketch not implemented")
}
func (UnimplementedHllServiceServer) MergeSketch(context.Context, *MergeRequest) (*MergeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MergeSketch not implemented")
}
func (UnimplementedHllServiceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedHllServiceServer) mustEmbedUnimplementedHllServiceServer() {}
func (UnimplementedHllServiceServer) testEmbeddedByValue()                    {}

// UnsafeHllServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HllServiceServer will
// result in compilation errors.
type UnsafeHllServiceServer interface {
	mustEmbedUnimplementedHllServiceServer()
}

func RegisterHllServiceServer(s grpc.ServiceRegistrar, srv HllServiceServer) {
	// If the following call pancis, it indicates UnimplementedHllServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HllService_ServiceDesc, srv)
}

func _HllService_Insert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HllServiceServer).Insert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HllService_Insert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HllServiceServer).Insert(ctx, req.(*InsertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HllService_GetEstimate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEstimateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HllServiceServer).GetEstimate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HllService_GetEstimate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HllServiceServer).GetEstimate(ctx, req.(*GetEstimateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HllService_Reset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HllServiceServer).Reset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HllService_Reset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HllServiceServer).Reset(ctx, req.(*ResetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HllService_GetSketch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSketchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HllServiceServer).GetSketch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HllService_GetSketch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HllServiceServer).GetSketch(ctx, req.(*GetSketchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HllService_MergeSketch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MergeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HllServiceServer).MergeSketch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HllService_MergeSketch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HllServiceServer).MergeSketch(ctx, req.(*MergeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HllService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HllServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HllService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HllServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HllService_ServiceDesc is the grpc.ServiceDesc for HllService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HllService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hllservice.HllService",
	HandlerType: (*HllServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Insert",
			Handler:    _HllService_Insert_Handler,
		},
		{
			MethodName: "GetEstimate",
			Handler:    _HllService_GetEstimate_Handler,
		},
		{
			MethodName: "Reset",
			Handler:    _HllService_Reset_Handler,
		},
		{
			MethodName: "GetSketch",
			Handler:    _HllService_GetSketch_Handler,
		},
		{
			MethodName: "MergeSketch",
			Handler:    _HllService_MergeSketch_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _HllService_Health_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server.proto",
}
