// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: server.proto

// Package name for the protobuf definitions

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthResponse_ServingStatus int32

const (
	HealthResponse_UNKNOWN     HealthResponse_ServingStatus = 0
	HealthResponse_SERVING     HealthResponse_ServingStatus = 1
	HealthResponse_NOT_SERVING HealthResponse_ServingStatus = 2
)

// Enum value maps for HealthResponse_ServingStatus.
var (
	HealthResponse_ServingStatus_name = map[int32]string{
		0: "UNKNOWN",
		1: "SERVING",
		2: "NOT_SERVING",
	}
	HealthResponse_ServingStatus_value = map[string]int32{
		"UNKNOWN":     0,
		"SERVING":     1,
		"NOT_SERVING": 2,
	}
)

func (x HealthResponse_ServingStatus) Enum() *HealthResponse_ServingStatus {
	p := new(HealthResponse_ServingStatus)
	*p = x
	return p
}

func (x HealthResponse_ServingStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthResponse_ServingStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_server_proto_enumTypes[0].Descriptor()
}

func (HealthResponse_ServingStatus) Type() protoreflect.EnumType {
	return &file_server_proto_enumTypes[0]
}

func (x HealthResponse_ServingStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthResponse_ServingStatus.Descriptor instead.
func (HealthResponse_ServingStatus) EnumDescriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{12, 0}
}

// Sketch is the "shipping container" for your HLL++ data.
// It can represent either the sparse or dense state.
type Sketch struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The target precision (p, e.g., 14).
	// Used to ensure merged sketches are compatible.
	P int32 `protobuf:"varint,1,opt,name=p,proto3" json:"p,omitempty"`
	// The sparse precision (p', e.g., 25).
	// Used to correctly decode sparse lists.
	PPrime int32 `protobuf:"varint,2,opt,name=p_prime,json=pPrime,proto3" json:"p_prime,omitempty"`
	// The data itself, using 'oneof' to save space.
	// Only one of these fields will be set.
	//
	// Types that are valid to be assigned to Data:
	//
	//	*Sketch_SparseData
	//	*Sketch_DenseData
	Data          isSketch_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sketch) Reset() {
	*x = Sketch{}
	mi := &file_server_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sketch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sketch) ProtoMessage() {}

func (x *Sketch) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sketch.ProtoReflect.Descriptor instead.
func (*Sketch) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{0}
}

func (x *Sketch) GetP() int32 {
	if x != nil {
		return x.P
	}
	return 0
}

func (x *Sketch) GetPPrime() int32 {
	if x != nil {
		return x.PPrime
	}
	return 0
}

func (x *Sketch) GetData() isSketch_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Sketch) GetSparseData() *SparseData {
	if x != nil {
		if x, ok := x.Data.(*Sketch_SparseData); ok {
			return x.SparseData
		}
	}
	return nil
}

func (x *Sketch) GetDenseData() []byte {
	if x != nil {
		if x, ok := x.Data.(*Sketch_DenseData); ok {
			return x.DenseData
		}
	}
	return nil
}

type isSketch_Data interface {
	isSketch_Data()
}

type Sketch_SparseData struct {
	// For FormatSparse
	SparseData *SparseData `protobuf:"bytes,3,opt,name=sparse_data,json=sparseData,proto3,oneof"`
}

type Sketch_DenseData struct {
	// For FormatDense
	// This is the raw byte slice from your 'register.Registers' _data field.
	DenseData []byte `protobuf:"bytes,4,opt,name=dense_data,json=denseData,proto3,oneof"`
}

func (*Sketch_SparseData) isSketch_Data() {}

func (*Sketch_DenseData) isSketch_Data() {}

// Represents the data needed for a sparse HLL.
type SparseData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// This is the `sorted_list` of encoded uint32 values.
	// The `temp_set` should be merged into this list *before* sending.
	SortedList    []uint32 `protobuf:"varint,1,rep,packed,name=sorted_list,json=sortedList,proto3" json:"sorted_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SparseData) Reset() {
	*x = SparseData{}
	mi := &file_server_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SparseData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SparseData) ProtoMessage() {}

func (x *SparseData) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SparseData.ProtoReflect.Descriptor instead.
func (*SparseData) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{1}
}

func (x *SparseData) GetSortedList() []uint32 {
	if x != nil {
		return x.SortedList
	}
	return nil
}

// Insert
type InsertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertRequest) Reset() {
	*x = InsertRequest{}
	mi := &file_server_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertRequest) ProtoMessage() {}

func (x *InsertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertRequest.ProtoReflect.Descriptor instead.
func (*InsertRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{2}
}

func (x *InsertRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

type InsertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertResponse) Reset() {
	*x = InsertResponse{}
	mi := &file_server_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertResponse) ProtoMessage() {}

func (x *InsertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertResponse.ProtoReflect.Descriptor instead.
func (*InsertResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{3}
}

// GetEstimate
type GetEstimateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEstimateRequest) Reset() {
	*x = GetEstimateRequest{}
	mi := &file_server_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEstimateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEstimateRequest) ProtoMessage() {}

func (x *GetEstimateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEstimateRequest.ProtoReflect.Descriptor instead.
func (*GetEstimateRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{4}
}

type GetEstimateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Estimate      uint64                 `protobuf:"varint,1,opt,name=estimate,proto3" json:"estimate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEstimateResponse) Reset() {
	*x = GetEstimateResponse{}
	mi := &file_server_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEstimateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEstimateResponse) ProtoMessage() {}

func (x *GetEstimateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEstimateResponse.ProtoReflect.Descriptor instead.
func (*GetEstimateResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{5}
}

func (x *GetEstimateResponse) GetEstimate() uint64 {
	if x != nil {
		return x.Estimate
	}
	return 0
}

// Reset
type ResetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetRequest) Reset() {
	*x = ResetRequest{}
	mi := &file_server_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetRequest) ProtoMessage() {}

func (x *ResetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetRequest.ProtoReflect.Descriptor instead.
func (*ResetRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{6}
}

type ResetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetResponse) Reset() {
	*x = ResetResponse{}
	mi := &file_server_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetResponse) ProtoMessage() {}

func (x *ResetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetResponse.ProtoReflect.Descriptor instead.
func (*ResetResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{7}
}

// GetSketch
type GetSketchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSketchRequest) Reset() {
	*x = GetSketchRequest{}
	mi := &file_server_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSketchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSketchRequest) ProtoMessage() {}

func (x *GetSketchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSketchRequest.ProtoReflect.Descriptor instead.
func (*GetSketchRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{8}
}

// MergeSketch
type MergeRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Sketch *Sketch                `protobuf:"bytes,1,opt,name=sketch,proto3" json:"sketch,omitempty"`
	// Telemetry fields from the sending agent.
	NodeId        string  `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	LodaScore     float64 `protobuf:"fixed64,3,opt,name=loda_score,json=lodaScore,proto3" json:"loda_score,omitempty"`
	HstScore      float64 `protobuf:"fixed64,4,opt,name=hst_score,json=hstScore,proto3" json:"hst_score,omitempty"`
	EnsembleScore float64 `protobuf:"fixed64,5,opt,name=ensemble_score,json=ensembleScore,proto3" json:"ensemble_score,omitempty"`
	AnomalyState  int32   `protobuf:"varint,6,opt,name=anomaly_state,json=anomalyState,proto3" json:"anomaly_state,omitempty"` // 0=NORMAL, 1=UNDER_ATTACK, 2=RECOVERY
	PacketCount   uint64  `protobuf:"varint,7,opt,name=packet_count,json=packetCount,proto3" json:"packet_count,omitempty"`
	// Attack classification fields (Phase 3 extension).
	AttackType       string  `protobuf:"bytes,8,opt,name=attack_type,json=attackType,proto3" json:"attack_type,omitempty"`
	AttackConfidence float64 `protobuf:"fixed64,9,opt,name=attack_confidence,json=attackConfidence,proto3" json:"attack_confidence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MergeRequest) Reset() {
	*x = MergeRequest{}
	mi := &file_server_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MergeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MergeRequest) ProtoMessage() {}

func (x *MergeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MergeRequest.ProtoReflect.Descriptor instead.
func (*MergeRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{9}
}

func (x *MergeRequest) GetSketch() *Sketch {
	if x != nil {
		return x.Sketch
	}
	return nil
}

func (x *MergeRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *MergeRequest) GetLodaScore() float64 {
	if x != nil {
		return x.LodaScore
	}
	return 0
}

func (x *MergeRequest) GetHstScore() float64 {
	if x != nil {
		return x.HstScore
	}
	return 0
}

func (x *MergeRequest) GetEnsembleScore() float64 {
	if x != nil {
		return x.EnsembleScore
	}
	return 0
}

func (x *MergeRequest) GetAnomalyState() int32 {
	if x != nil {
		return x.AnomalyState
	}
	return 0
}

func (x *MergeRequest) GetPacketCount() uint64 {
	if x != nil {
		return x.PacketCount
	}
	return 0
}

func (x *MergeRequest) GetAttackType() string {
	if x != nil {
		return x.AttackType
	}
	return ""
}

func (x *MergeRequest) GetAttackConfidence() float64 {
	if x != nil {
		return x.AttackConfidence
	}
	return 0
}

type MergeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MergeResponse) Reset() {
	*x = MergeResponse{}
	mi := &file_server_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MergeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MergeResponse) ProtoMessage() {}

func (x *MergeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MergeResponse.ProtoReflect.Descriptor instead.
func (*MergeResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{10}
}

// Health
type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_server_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{11}
}

type HealthResponse struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Status        HealthResponse_ServingStatus `protobuf:"varint,1,opt,name=status,proto3,enum=hllservice.HealthResponse_ServingStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_server_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{12}
}

func (x *HealthResponse) GetStatus() HealthResponse_ServingStatus {
	if x != nil {
		return x.Status
	}
	return HealthResponse_UNKNOWN
}

// DefenseCommand — aggregator response to node defense queries.
type DefenseCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Activated     bool                   `protobuf:"varint,1,opt,name=activated,proto3" json:"activated,omitempty"`
	GlobalScore   float64                `protobuf:"fixed64,2,opt,name=global_score,json=globalScore,proto3" json:"global_score,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DefenseCommand) Reset() {
	*x = DefenseCommand{}
	mi := &file_server_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DefenseCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DefenseCommand) ProtoMessage() {}

func (x *DefenseCommand) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DefenseCommand.ProtoReflect.Descriptor instead.
func (*DefenseCommand) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{13}
}

func (x *DefenseCommand) GetActivated() bool {
	if x != nil {
		return x.Activated
	}
	return false
}

func (x *DefenseCommand) GetGlobalScore() float64 {
	if x != nil {
		return x.GlobalScore
	}
	return 0
}

func (x *DefenseCommand) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// NodeRequest — identifies a node querying for defense commands.
type NodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeRequest) Reset() {
	*x = NodeRequest{}
	mi := &file_server_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeRequest) ProtoMessage() {}

func (x *NodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeRequest.ProtoReflect.Descriptor instead.
func (*NodeRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{14}
}

func (x *NodeRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

// InjectIP — simulation mode: inject a synthetic IP into an agent.
type InjectIPRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	ByteLen       uint64                 `protobuf:"varint,2,opt,name=byte_len,json=byteLen,proto3" json:"byte_len,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InjectIPRequest) Reset() {
	*x = InjectIPRequest{}
	mi := &file_server_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InjectIPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InjectIPRequest) ProtoMessage() {}

func (x *InjectIPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InjectIPRequest.ProtoReflect.Descriptor instead.
func (*InjectIPRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{15}
}

func (x *InjectIPRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *InjectIPRequest) GetByteLen() uint64 {
	if x != nil {
		return x.ByteLen
	}
	return 0
}

type InjectIPResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InjectIPResponse) Reset() {
	*x = InjectIPResponse{}
	mi := &file_server_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InjectIPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InjectIPResponse) ProtoMessage() {}

func (x *InjectIPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InjectIPResponse.ProtoReflect.Descriptor instead.
func (*InjectIPResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{16}
}

// InjectIPs — simulation mode: inject a batch of synthetic IPs.
type InjectIPsBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ips           []string               `protobuf:"bytes,1,rep,name=ips,proto3" json:"ips,omitempty"`
	ByteLen       uint64                 `protobuf:"varint,2,opt,name=byte_len,json=byteLen,proto3" json:"byte_len,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InjectIPsBatchRequest) Reset() {
	*x = InjectIPsBatchRequest{}
	mi := &file_server_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InjectIPsBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InjectIPsBatchRequest) ProtoMessage() {}

func (x *InjectIPsBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InjectIPsBatchRequest.ProtoReflect.Descriptor instead.
func (*InjectIPsBatchRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{17}
}

func (x *InjectIPsBatchRequest) GetIps() []string {
	if x != nil {
		return x.Ips
	}
	return nil
}

func (x *InjectIPsBatchRequest) GetByteLen() uint64 {
	if x != nil {
		return x.ByteLen
	}
	return 0
}

var File_server_proto protoreflect.FileDescriptor

const file_server_proto_rawDesc = "" +
	"\n" +
	"\fserver.proto\x12\n" +
	"hllservice\"\x93\x01\n" +
	"\x06Sketch\x12\f\n" +
	"\x01p\x18\x01 \x01(\x05R\x01p\x12\x17\n" +
	"\ap_prime\x18\x02 \x01(\x05R\x06pPrime\x129\n" +
	"\vsparse_data\x18\x03 \x01(\v2\x16.hllservice.SparseDataH\x00R\n" +
	"sparseData\x12\x1f\n" +
	"\n" +
	"dense_data\x18\x04 \x01(\fH\x00R\tdenseDataB\x06\n" +
	"\x04data\"-\n" +
	"\n" +
	"SparseData\x12\x1f\n" +
	"\vsorted_list\x18\x01 \x03(\rR\n" +
	"sortedList\"\x1f\n" +
	"\rInsertRequest\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\"\x10\n" +
	"\x0eInsertResponse\"\x14\n" +
	"\x12GetEstimateRequest\"1\n" +
	"\x13GetEstimateResponse\x12\x1a\n" +
	"\bestimate\x18\x01 \x01(\x04R\bestimate\"\x0e\n" +
	"\fResetRequest\"\x0f\n" +
	"\rResetResponse\"\x12\n" +
	"\x10GetSketchRequest\"\xfe\x01\n" +
	"\fMergeRequest\x12*\n" +
	"\x06sketch\x18\x01 \x01(\v2\x12.hllservice.SketchR\x06sketch\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12\x1d\n" +
	"\n" +
	"loda_score\x18\x03 \x01(\x01R\tlodaScore\x12\x1b\n" +
	"\thst_score\x18\x04 \x01(\x01R\bhstScore\x12%\n" +
	"\x0eensemble_score\x18\x05 \x01(\x01R\rensembleScore\x12#\n" +
	"\ranomaly_state\x18\x06 \x01(\x05R\fanomalyState\x12!\n" +
	"\fpacket_count\x18\a \x01(\x04R\vpacketCount\"\x0f\n" +
	"\rMergeResponse\"\x0f\n" +
	"\rHealthRequest\"\x8e\x01\n" +
	"\x0eHealthResponse\x12@\n" +
	"\x06status\x18\x01 \x01(\x0e2(.hllservice.HealthResponse.ServingStatusR\x06status\":\n" +
	"\rServingStatus\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aSERVING\x10\x01\x12\x0f\n" +
	"\vNOT_SERVING\x10\x02\"i\n" +
	"\x0eDefenseCommand\x12\x1c\n" +
	"\tactivated\x18\x01 \x01(\bR\tactivated\x12!\n" +
	"\fglobal_score\x18\x02 \x01(\x01R\vglobalScore\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"&\n" +
	"\vNodeRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"<\n" +
	"\x0fInjectIPRequest\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x19\n" +
	"\bbyte_len\x18\x02 \x01(\x04R\abyteLen\"\x12\n" +
	"\x10InjectIPResponse\"D\n" +
	"\x15InjectIPsBatchRequest\x12\x10\n" +
	"\x03ips\x18\x01 \x03(\tR\x03ips\x12\x19\n" +
	"\bbyte_len\x18\x02 \x01(\x04R\abyteLen2\xfe\x04\n" +
	"\n" +
	"HllService\x12?\n" +
	"\x06Insert\x12\x19.hllservice.InsertRequest\x1a\x1a.hllservice.InsertResponse\x12N\n" +
	"\vGetEstimate\x12\x1e.hllservice.GetEstimateRequest\x1a\x1f.hllservice.GetEstimateResponse\x12<\n" +
	"\x05Reset\x12\x18.hllservice.ResetRequest\x1a\x19.hllservice.ResetResponse\x12=\n" +
	"\tGetSketch\x12\x1c.hllservice.GetSketchRequest\x1a\x12.hllservice.Sketch\x12B\n" +
	"\vMergeSketch\x12\x18.hllservice.MergeRequest\x1a\x19.hllservice.MergeResponse\x12?\n" +
	"\x06Health\x12\x19.hllservice.HealthRequest\x1a\x1a.hllservice.HealthResponse\x12H\n" +
	"\x11GetDefenseCommand\x12\x17.hllservice.NodeRequest\x1a\x1a.hllservice.DefenseCommand\x12E\n" +
	"\bInjectIP\x12\x1b.hllservice.InjectIPRequest\x1a\x1c.hllservice.InjectIPResponse\x12L\n" +
	"\tInjectIPs\x12!.hllservice.InjectIPsBatchRequest\x1a\x1c.hllservice.InjectIPResponseB\x13Z\x11HLL-BTP/server/pbb\x06proto3"

var (
	file_server_proto_rawDescOnce sync.Once
	file_server_proto_rawDescData []byte
)

func file_server_proto_rawDescGZIP() []byte {
	file_server_proto_rawDescOnce.Do(func() {
		file_server_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_server_proto_rawDesc), len(file_server_proto_rawDesc)))
	})
	return file_server_proto_rawDescData
}

var file_server_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_server_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_server_proto_goTypes = []any{
	(HealthResponse_ServingStatus)(0), // 0: hllservice.HealthResponse.ServingStatus
	(*Sketch)(nil),                    // 1: hllservice.Sketch
	(*SparseData)(nil),                // 2: hllservice.SparseData
	(*InsertRequest)(nil),             // 3: hllservice.InsertRequest
	(*InsertResponse)(nil),            // 4: hllservice.InsertResponse
	(*GetEstimateRequest)(nil),        // 5: hllservice.GetEstimateRequest
	(*GetEstimateResponse)(nil),       // 6: hllservice.GetEstimateResponse
	(*ResetRequest)(nil),              // 7: hllservice.ResetRequest
	(*ResetResponse)(nil),             // 8: hllservice.ResetResponse
	(*GetSketchRequest)(nil),          // 9: hllservice.GetSketchRequest
	(*MergeRequest)(nil),              // 10: hllservice.MergeRequest
	(*MergeResponse)(nil),             // 11: hllservice.MergeResponse
	(*HealthRequest)(nil),             // 12: hllservice.HealthRequest
	(*HealthResponse)(nil),            // 13: hllservice.HealthResponse
	(*DefenseCommand)(nil),            // 14: hllservice.DefenseCommand
	(*NodeRequest)(nil),               // 15: hllservice.NodeRequest
	(*InjectIPRequest)(nil),           // 16: hllservice.InjectIPRequest
	(*InjectIPResponse)(nil),          // 17: hllservice.InjectIPResponse
	(*InjectIPsBatchRequest)(nil),     // 18: hllservice.InjectIPsBatchRequest
}
var file_server_proto_depIdxs = []int32{
	2,  // 0: hllservice.Sketch.sparse_data:type_name -> hllservice.SparseData
	1,  // 1: hllservice.MergeRequest.sketch:type_name -> hllservice.Sketch
	0,  // 2: hllservice.HealthResponse.status:type_name -> hllservice.HealthResponse.ServingStatus
	3,  // 3: hllservice.HllService.Insert:input_type -> hllservice.InsertRequest
	5,  // 4: hllservice.HllService.GetEstimate:input_type -> hllservice.GetEstimateRequest
	7,  // 5: hllservice.HllService.Reset:input_type -> hllservice.ResetRequest
	9,  // 6: hllservice.HllService.GetSketch:input_type -> hllservice.GetSketchRequest
	10, // 7: hllservice.HllService.MergeSketch:input_type -> hllservice.MergeRequest
	12, // 8: hllservice.HllService.Health:input_type -> hllservice.HealthRequest
	15, // 9: hllservice.HllService.GetDefenseCommand:input_type -> hllservice.NodeRequest
	16, // 10: hllservice.HllService.InjectIP:input_type -> hllservice.InjectIPRequest
	18, // 11: hllservice.HllService.InjectIPs:input_type -> hllservice.InjectIPsBatchRequest
	4,  // 12: hllservice.HllService.Insert:output_type -> hllservice.InsertResponse
	6,  // 13: hllservice.HllService.GetEstimate:output_type -> hllservice.GetEstimateResponse
	8,  // 14: hllservice.HllService.Reset:output_type -> hllservice.ResetResponse
	1,  // 15: hllservice.HllService.GetSketch:output_type -> hllservice.Sketch
	11, // 16: hllservice.HllService.MergeSketch:output_type -> hllservice.MergeResponse
	13, // 17: hllservice.HllService.Health:output_type -> hllservice.HealthResponse
	14, // 18: hllservice.HllService.GetDefenseCommand:output_type -> hllservice.DefenseCommand
	17, // 19: hllservice.HllService.InjectIP:output_type -> hllservice.InjectIPResponse
	17, // 20: hllservice.HllService.InjectIPs:output_type -> hllservice.InjectIPResponse
	12, // [12:21] is the sub-list for method output_type
	3,  // [3:12] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_server_proto_init() }
func file_server_proto_init() {
	if File_server_proto != nil {
		return
	}
	file_server_proto_msgTypes[0].OneofWrappers = []any{
		(*Sketch_SparseData)(nil),
		(*Sketch_DenseData)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_server_proto_rawDesc), len(file_server_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_server_proto_goTypes,
		DependencyIndexes: file_server_proto_depIdxs,
		EnumInfos:         file_server_proto_enumTypes,
		MessageInfos:      file_server_proto_msgTypes,
	}.Build()
	File_server_proto = out.File
	file_server_proto_goTypes = nil
	file_server_proto_depIdxs = nil
}
