// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: server.proto

// Package name for the protobuf definitions

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthResponse_ServingStatus int32

const (
	HealthResponse_UNKNOWN     HealthResponse_ServingStatus = 0
	HealthResponse_SERVING     HealthResponse_ServingStatus = 1
	HealthResponse_NOT_SERVING HealthResponse_ServingStatus = 2
)

// Enum value maps for HealthResponse_ServingStatus.
var (
	HealthResponse_ServingStatus_name = map[int32]string{
		0: "UNKNOWN",
		1: "SERVING",
		2: "NOT_SERVING",
	}
	HealthResponse_ServingStatus_value = map[string]int32{
		"UNKNOWN":     0,
		"SERVING":     1,
		"NOT_SERVING": 2,
	}
)

func (x HealthResponse_ServingStatus) Enum() *HealthResponse_ServingStatus {
	p := new(HealthResponse_ServingStatus)
	*p = x
	return p
}

func (x HealthResponse_ServingStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthResponse_ServingStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_server_proto_enumTypes[0].Descriptor()
}

func (HealthResponse_ServingStatus) Type() protoreflect.EnumType {
	return &file_server_proto_enumTypes[0]
}

func (x HealthResponse_ServingStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthResponse_ServingStatus.Descriptor instead.
func (HealthResponse_ServingStatus) EnumDescriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{12, 0}
}

// Sketch is the "shipping container" for your HLL++ data.
// It can represent either the sparse or dense state.
type Sketch struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The target precision (p, e.g., 14).
	// Used to ensure merged sketches are compatible.
	P int32 `protobuf:"varint,1,opt,name=p,proto3" json:"p,omitempty"`
	// The sparse precision (p', e.g., 25).
	// Used to correctly decode sparse lists.
	PPrime int32 `protobuf:"varint,2,opt,name=p_prime,json=pPrime,proto3" json:"p_prime,omitempty"`
	// The data itself, using 'oneof' to save space.
	// Only one of these fields will be set.
	//
	// Types that are valid to be assigned to Data:
	//
	//	*Sketch_SparseData
	//	*Sketch_DenseData
	Data          isSketch_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sketch) Reset() {
	*x = Sketch{}
	mi := &file_server_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sketch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sketch) ProtoMessage() {}

func (x *Sketch) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sketch.ProtoReflect.Descriptor instead.
func (*Sketch) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{0}
}

func (x *Sketch) GetP() int32 {
	if x != nil {
		return x.P
	}
	return 0
}

func (x *Sketch) GetPPrime() int32 {
	if x != nil {
		return x.PPrime
	}
	return 0
}

func (x *Sketch) GetData() isSketch_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Sketch) GetSparseData() *SparseData {
	if x != nil {
		if x, ok := x.Data.(*Sketch_SparseData); ok {
			return x.SparseData
		}
	}
	return nil
}

func (x *Sketch) GetDenseData() []byte {
	if x != nil {
		if x, ok := x.Data.(*Sketch_DenseData); ok {
			return x.DenseData
		}
	}
	return nil
}

type isSketch_Data interface {
	isSketch_Data()
}

type Sketch_SparseData struct {
	// For FormatSparse
	SparseData *SparseData `protobuf:"bytes,3,opt,name=sparse_data,json=sparseData,proto3,oneof"`
}

type Sketch_DenseData struct {
	// For FormatDense
	// This is the raw byte slice from your 'register.Registers' _data field.
	DenseData []byte `protobuf:"bytes,4,opt,name=dense_data,json=denseData,proto3,oneof"`
}

func (*Sketch_SparseData) isSketch_Data() {}

func (*Sketch_DenseData) isSketch_Data() {}

// Represents the data needed for a sparse HLL.
type SparseData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// This is the `sorted_list` of encoded uint32 values.
	// The `temp_set` should be merged into this list *before* sending.
	SortedList    []uint32 `protobuf:"varint,1,rep,packed,name=sorted_list,json=sortedList,proto3" json:"sorted_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SparseData) Reset() {
	*x = SparseData{}
	mi := &file_server_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SparseData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SparseData) ProtoMessage() {}

func (x *SparseData) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SparseData.ProtoReflect.Descriptor instead.
func (*SparseData) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{1}
}

func (x *SparseData) GetSortedList() []uint32 {
	if x != nil {
		return x.SortedList
	}
	return nil
}

// Insert
type InsertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertRequest) Reset() {
	*x = InsertRequest{}
	mi := &file_server_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertRequest) ProtoMessage() {}

func (x *InsertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertRequest.ProtoReflect.Descriptor instead.
func (*InsertRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{2}
}

func (x *InsertRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

type InsertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertResponse) Reset() {
	*x = InsertResponse{}
	mi := &file_server_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertResponse) ProtoMessage() {}

func (x *InsertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertResponse.ProtoReflect.Descriptor instead.
func (*InsertResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{3}
}

// GetEstimate
type GetEstimateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEstimateRequest) Reset() {
	*x = GetEstimateRequest{}
	mi := &file_server_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEstimateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEstimateRequest) ProtoMessage() {}

func (x *GetEstimateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEstimateRequest.ProtoReflect.Descriptor instead.
func (*GetEstimateRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{4}
}

type GetEstimateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Estimate      uint64                 `protobuf:"varint,1,opt,name=estimate,proto3" json:"estimate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEstimateResponse) Reset() {
	*x = GetEstimateResponse{}
	mi := &file_server_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEstimateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEstimateResponse) ProtoMessage() {}

func (x *GetEstimateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEstimateResponse.ProtoReflect.Descriptor instead.
func (*GetEstimateResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{5}
}

func (x *GetEstimateResponse) GetEstimate() uint64 {
	if x != nil {
		return x.Estimate
	}
	return 0
}

// Reset
type ResetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetRequest) Reset() {
	*x = ResetRequest{}
	mi := &file_server_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetRequest) ProtoMessage() {}

func (x *ResetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetRequest.ProtoReflect.Descriptor instead.
func (*ResetRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{6}
}

type ResetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetResponse) Reset() {
	*x = ResetResponse{}
	mi := &file_server_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetResponse) ProtoMessage() {}

func (x *ResetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetResponse.ProtoReflect.Descriptor instead.
func (*ResetResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{7}
}

// GetSketch
type GetSketchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSketchRequest) Reset() {
	*x = GetSketchRequest{}
	mi := &file_server_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSketchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSketchRequest) ProtoMessage() {}

func (x *GetSketchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSketchRequest.ProtoReflect.Descriptor instead.
func (*GetSketchRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{8}
}

// MergeSketch
type MergeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sketch        *Sketch                `protobuf:"bytes,1,opt,name=sketch,proto3" json:"sketch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MergeRequest) Reset() {
	*x = MergeRequest{}
	mi := &file_server_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MergeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MergeRequest) ProtoMessage() {}

func (x *MergeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MergeRequest.ProtoReflect.Descriptor instead.
func (*MergeRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{9}
}

func (x *MergeRequest) GetSketch() *Sketch {
	if x != nil {
		return x.Sketch
	}
	return nil
}

type MergeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MergeResponse) Reset() {
	*x = MergeResponse{}
	mi := &file_server_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MergeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MergeResponse) ProtoMessage() {}

func (x *MergeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MergeResponse.ProtoReflect.Descriptor instead.
func (*MergeResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{10}
}

// Health
type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_server_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{11}
}

type HealthResponse struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Status        HealthResponse_ServingStatus `protobuf:"varint,1,opt,name=status,proto3,enum=hllservice.HealthResponse_ServingStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_server_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{12}
}

func (x *HealthResponse) GetStatus() HealthResponse_ServingStatus {
	if x != nil {
		return x.Status
	}
	return HealthResponse_UNKNOWN
}

// SubmitWindow — agent → aggregator sketch push
type SubmitWindowRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The window ID: time.UnixNano() / windowDuration.Nanoseconds()
	// Used by the aggregator to align sketches to the correct time bucket.
	WindowId      int64   `protobuf:"varint,1,opt,name=window_id,json=windowId,proto3" json:"window_id,omitempty"`
	Sketch        *Sketch `protobuf:"bytes,2,opt,name=sketch,proto3" json:"sketch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitWindowRequest) Reset() {
	*x = SubmitWindowRequest{}
	mi := &file_server_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitWindowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitWindowRequest) ProtoMessage() {}

func (x *SubmitWindowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitWindowRequest.ProtoReflect.Descriptor instead.
func (*SubmitWindowRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{13}
}

func (x *SubmitWindowRequest) GetWindowId() int64 {
	if x != nil {
		return x.WindowId
	}
	return 0
}

func (x *SubmitWindowRequest) GetSketch() *Sketch {
	if x != nil {
		return x.Sketch
	}
	return nil
}

type SubmitWindowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitWindowResponse) Reset() {
	*x = SubmitWindowResponse{}
	mi := &file_server_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitWindowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitWindowResponse) ProtoMessage() {}

func (x *SubmitWindowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitWindowResponse.ProtoReflect.Descriptor instead.
func (*SubmitWindowResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{14}
}

var File_server_proto protoreflect.FileDescriptor

const file_server_proto_rawDesc = "" +
	"\n" +
	"\fserver.proto\x12\n" +
	"hllservice\"\x93\x01\n" +
	"\x06Sketch\x12\f\n" +
	"\x01p\x18\x01 \x01(\x05R\x01p\x12\x17\n" +
	"\ap_prime\x18\x02 \x01(\x05R\x06pPrime\x129\n" +
	"\vsparse_data\x18\x03 \x01(\v2\x16.hllservice.SparseDataH\x00R\n" +
	"sparseData\x12\x1f\n" +
	"\n" +
	"dense_data\x18\x04 \x01(\fH\x00R\tdenseDataB\x06\n" +
	"\x04data\"-\n" +
	"\n" +
	"SparseData\x12\x1f\n" +
	"\vsorted_list\x18\x01 \x03(\rR\n" +
	"sortedList\"\x1f\n" +
	"\rInsertRequest\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\"\x10\n" +
	"\x0eInsertResponse\"\x14\n" +
	"\x12GetEstimateRequest\"1\n" +
	"\x13GetEstimateResponse\x12\x1a\n" +
	"\bestimate\x18\x01 \x01(\x04R\bestimate\"\x0e\n" +
	"\fResetRequest\"\x0f\n" +
	"\rResetResponse\"\x12\n" +
	"\x10GetSketchRequest\":\n" +
	"\fMergeRequest\x12*\n" +
	"\x06sketch\x18\x01 \x01(\v2\x12.hllservice.SketchR\x06sketch\"\x0f\n" +
	"\rMergeResponse\"\x0f\n" +
	"\rHealthRequest\"\x8e\x01\n" +
	"\x0eHealthResponse\x12@\n" +
	"\x06status\x18\x01 \x01(\x0e2(.hllservice.HealthResponse.ServingStatusR\x06status\":\n" +
	"\rServingStatus\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aSERVING\x10\x01\x12\x0f\n" +
	"\vNOT_SERVING\x10\x02\"^\n" +
	"\x13SubmitWindowRequest\x12\x1b\n" +
	"\twindow_id\x18\x01 \x01(\x03R\bwindowId\x12*\n" +
	"\x06sketch\x18\x02 \x01(\v2\x12.hllservice.SketchR\x06sketch\"\x16\n" +
	"\x14SubmitWindowResponse2\xf2\x03\n" +
	"\n" +
	"HllService\x12?\n" +
	"\x06Insert\x12\x19.hllservice.InsertRequest\x1a\x1a.hllservice.InsertResponse\x12N\n" +
	"\vGetEstimate\x12\x1e.hllservice.GetEstimateRequest\x1a\x1f.hllservice.GetEstimateResponse\x12<\n" +
	"\x05Reset\x12\x18.hllservice.ResetRequest\x1a\x19.hllservice.ResetResponse\x12=\n" +
	"\tGetSketch\x12\x1c.hllservice.GetSketchRequest\x1a\x12.hllservice.Sketch\x12B\n" +
	"\vMergeSketch\x12\x18.hllservice.MergeRequest\x1a\x19.hllservice.MergeResponse\x12?\n" +
	"\x06Health\x12\x19.hllservice.HealthRequest\x1a\x1a.hllservice.HealthResponse\x12Q\n" +
	"\fSubmitWindow\x12\x1f.hllservice.SubmitWindowRequest\x1a .hllservice.SubmitWindowResponseB\x13Z\x11HLL-BTP/server/pbb\x06proto3"

var (
	file_server_proto_rawDescOnce sync.Once
	file_server_proto_rawDescData []byte
)

func file_server_proto_rawDescGZIP() []byte {
	file_server_proto_rawDescOnce.Do(func() {
		file_server_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_server_proto_rawDesc), len(file_server_proto_rawDesc)))
	})
	return file_server_proto_rawDescData
}

var file_server_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_server_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_server_proto_goTypes = []any{
	(HealthResponse_ServingStatus)(0), // 0: hllservice.HealthResponse.ServingStatus
	(*Sketch)(nil),                    // 1: hllservice.Sketch
	(*SparseData)(nil),                // 2: hllservice.SparseData
	(*InsertRequest)(nil),             // 3: hllservice.InsertRequest
	(*InsertResponse)(nil),            // 4: hllservice.InsertResponse
	(*GetEstimateRequest)(nil),        // 5: hllservice.GetEstimateRequest
	(*GetEstimateResponse)(nil),       // 6: hllservice.GetEstimateResponse
	(*ResetRequest)(nil),              // 7: hllservice.ResetRequest
	(*ResetResponse)(nil),             // 8: hllservice.ResetResponse
	(*GetSketchRequest)(nil),          // 9: hllservice.GetSketchRequest
	(*MergeRequest)(nil),              // 10: hllservice.MergeRequest
	(*MergeResponse)(nil),             // 11: hllservice.MergeResponse
	(*HealthRequest)(nil),             // 12: hllservice.HealthRequest
	(*HealthResponse)(nil),            // 13: hllservice.HealthResponse
	(*SubmitWindowRequest)(nil),       // 14: hllservice.SubmitWindowRequest
	(*SubmitWindowResponse)(nil),      // 15: hllservice.SubmitWindowResponse
}
var file_server_proto_depIdxs = []int32{
	2,  // 0: hllservice.Sketch.sparse_data:type_name -> hllservice.SparseData
	1,  // 1: hllservice.MergeRequest.sketch:type_name -> hllservice.Sketch
	0,  // 2: hllservice.HealthResponse.status:type_name -> hllservice.HealthResponse.ServingStatus
	1,  // 3: hllservice.SubmitWindowRequest.sketch:type_name -> hllservice.Sketch
	3,  // 4: hllservice.HllService.Insert:input_type -> hllservice.InsertRequest
	5,  // 5: hllservice.HllService.GetEstimate:input_type -> hllservice.GetEstimateRequest
	7,  // 6: hllservice.HllService.Reset:input_type -> hllservice.ResetRequest
	9,  // 7: hllservice.HllService.GetSketch:input_type -> hllservice.GetSketchRequest
	10, // 8: hllservice.HllService.MergeSketch:input_type -> hllservice.MergeRequest
	12, // 9: hllservice.HllService.Health:input_type -> hllservice.HealthRequest
	14, // 10: hllservice.HllService.SubmitWindow:input_type -> hllservice.SubmitWindowRequest
	4,  // 11: hllservice.HllService.Insert:output_type -> hllservice.InsertResponse
	6,  // 12: hllservice.HllService.GetEstimate:output_type -> hllservice.GetEstimateResponse
	8,  // 13: hllservice.HllService.Reset:output_type -> hllservice.ResetResponse
	1,  // 14: hllservice.HllService.GetSketch:output_type -> hllservice.Sketch
	11, // 15: hllservice.HllService.MergeSketch:output_type -> hllservice.MergeResponse
	13, // 16: hllservice.HllService.Health:output_type -> hllservice.HealthResponse
	15, // 17: hllservice.HllService.SubmitWindow:output_type -> hllservice.SubmitWindowResponse
	11, // [11:18] is the sub-list for method output_type
	4,  // [4:11] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_server_proto_init() }
func file_server_proto_init() {
	if File_server_proto != nil {
		return
	}
	file_server_proto_msgTypes[0].OneofWrappers = []any{
		(*Sketch_SparseData)(nil),
		(*Sketch_DenseData)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_server_proto_rawDesc), len(file_server_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_server_proto_goTypes,
		DependencyIndexes: file_server_proto_depIdxs,
		EnumInfos:         file_server_proto_enumTypes,
		MessageInfos:      file_server_proto_msgTypes,
	}.Build()
	File_server_proto = out.File
	file_server_proto_goTypes = nil
	file_server_proto_depIdxs = nil
}
